version: "3.7"
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'chatterbox'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  api:
    build: ./api
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    command: npm run serve
